version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(pip)'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(actions)'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(docker)'