{
 "title": "AirPurifier",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AQI (PM2.5)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airpurifier_aqi{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airpurifier_temp{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airpurifier_humidity{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "Filter used hours",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airpurifier_filter_hours_used{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "Filter remaining percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airpurifier_filter_remaining{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "Filter left days",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airpurifier_filter_left_time{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "AQI (PM2.5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "airpurifier_aqi{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "Filter remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "airpurifier_filter_remaining{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "airpurifier_temp{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "airpurifier_humidity{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "Filter used hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "airpurifier_filter_hours_used{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "Filter left days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "airpurifier_filter_left_time{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airpurifier_fan_speed{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "airpurifier_fan_speed{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "Power Stability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "airpurifier_power{instance=\"10.20.30.11:9091\"}"
    }
   ]
  },
  {
   "title": "Is power on",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "airpurifier_power{instance=\"10.20.30.11:9091\"}"
    }
   ]
  }
 ]
}