name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # this is a simple way of using date and time to do versioning.
    - name: Modify scripts and get version
      id: version
      run: |
        output=$(date -u '+%Y%m%d%H%M%S')
        echo ::set-output name=date_version::$output

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2.7.0
      with:
        context: ./
        file: ./Dockerfile
        platforms: linux/amd64, linux/arm64, linux/arm/v7 
        push: true
        tags: |
          ghcr.io/mpthlee/prometheus_airpurifier_miot_exporter:latest
          ghcr.io/mpthlee/prometheus_airpurifier_miot_exporter:${{steps.version.outputs.date_version}}