name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # this is a simple way of using date and time to do versioning.
    - name: Modify scripts and get version
      id: version
      run: |
        output=$(date -u '+%Y%m%d%H%M%S')
        echo ::set-output name=date_version::$output

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        platforms: linux/amd64, linux/arm64
        push: true
        tags: |
          mpthlee/prometheus_airpurifier_miot_exporter:latest
          mpthlee/prometheus_airpurifier_miot_exporter:${{ github.sha }}
          mpthlee/prometheus_airpurifier_miot_exporter:${{ steps.version.outputs.date_version }}
          ghcr.io/mpthlee/prometheus_airpurifier_miot_exporter:latest
          ghcr.io/mpthlee/prometheus_airpurifier_miot_exporter:${{ github.sha }}
          ghcr.io/mpthlee/prometheus_airpurifier_miot_exporter:${{ steps.version.outputs.date_version }}
        cache-from: type=gha,scope=${{ github.workflow }}
        cache-to: type=gha,mode=max,scope=${{ github.workflow }}
